# Generated by Django 4.0.4 on 2022-06-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smileReason', models.CharField(max_length=200)),
                ('smile_Aprroval', models.BooleanField(default=False)),
                ('smileUserName', models.CharField(default='', max_length=100)),
                ('smileImage', models.ImageField(default='', upload_to='smile/images')),
                ('referal_code', models.CharField(blank=True, max_length=12)),
            ],
        ),
    ]
