# Generated by Django 4.0.4 on 2022-06-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('profile_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('FName', models.CharField(blank=True, max_length=15, unique=True)),
                ('LName', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('profile_image', models.ImageField(default='', upload_to='smile/images')),
                ('referal_code', models.CharField(blank=True, max_length=12)),
            ],
        ),
    ]
