# Generated by Django 4.0.4 on 2022-06-13 05:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
