# Generated by Django 4.0.4 on 2022-06-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0007_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smile',
            name='smileImage',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
