# Generated by Django 4.0.4 on 2022-06-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0008_alter_smile_smileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smile',
            name='smileImage',
            field=models.ImageField(default='', upload_to='smile/images'),
        ),
    ]
