# Generated by Django 4.0.4 on 2022-06-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0009_alter_smile_smileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='', upload_to='smile/images'),
        ),
    ]
