# Generated by Django 4.0.4 on 2022-06-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile', '0012_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
